name: Update Probabilities

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-probabilities:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("tidyverse"))'

      - name: Run R script
        run: Rscript script.R  # This runs your R script and updates `sched_2324_diff.csv`

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/sched_2324_diff.csv
          git commit -m "Update game probabilities" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
